resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm

variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - .github
    - .jenkins
    - docs
    - '.*.y*ml'
    - '*.md'
    - LICENSE

pr:
  autoCancel: true
  branches:
    include:
    - master
  paths:
    exclude:
    - .github
    - .jenkins
    - docs
    - '.*.y*ml'
    - '*.md'
    - LICENSE
  drafts: false

jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/rpp.yml@pipelines_repo
